카타시안의 곱 - 데이터를 복제하는 용도로 사용된다.
소계나 총계관련 함수를 지원하지 않는 경우 카타시안의 곱을 활용하여 집계처리를 해야한다.

SELECT DEPT, COLL FROM TEST11
,(SELECT ROWNUM RNO REMO TEMP WHERE ROWNUM<3)

SELECT T1.DEPT, T1.COLL
  FROM TEST11 T1
       ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) T2 --인라인뷰
       
SELECT T1.DEPT, T1.COLL
      ,DECODE(RNO,1,'1,2학년',2,'3,4학년') AS "학년"
      ,DECODE(RNO,1,FRE,2,JUN) AS "학년"
  FROM TEST11 T1
       ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) T2 --인라인뷰

SELECT T1.DEPT, T1.COLL
      ,DECODE(RNO,1,'1,2학년',2,'3,4학년') AS "학년"
      ,DECODE(RNO,1,FRE,2,JUN) AS "1,2학년"
      ,DECODE(RNO,1,SUP,2,SEN) AS "3,4학년"
  FROM TEST11 T1
       ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) T2           
ORDER BY DEPT DESC, "학년"
       
------------------------------------------------------------

SELECT * FROM T_ORDERBASKET A,
              (SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3)

SELECT * FROM T_ORDERBASKET A,
              (SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3)

SELECT INDATE_VC FROM T_ORDERBASKET
GROUP BY INDATE_VC

SELECT INDATE_VC FROM T_ORDERBASKET
GROUP BY INDATE_VC
UNION ALL
SELECT '총계' FROM DUAL

SELECT INDATE_VC, RNO FROM T_ORDERBASKET
                      ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3)

SELECT DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계') 
    FROM T_ORDERBASKET O
      ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) DUMY
      
SELECT DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계') 
    FROM T_ORDERBASKET O
      ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) DUMY
GROUP BY DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계')
ORDER BY DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계')

SELECT DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계')
       ,SUM(O.QTY_NU*PRICE_NU)||'원' 
    FROM T_ORDERBASKET O
      ,(SELECT ROWNUM RNO FROM TEMP WHERE ROWNUM<3) DUMY
GROUP BY DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계')
ORDER BY DECODE(DUMY.RNO,1,O.INDATE_VC,2,'총계')                                   


equal 조인

non-equal 조인

outer 조인

self 조인
