SELECT (INFECTED_LOC||'¿Õ¼º±³È¸') FROM CORONA

SELECT * FROM CORONA 

INSERT INTO CORONA (SERIAL_NUM, CONFIRMATION_DAY, LOC, INFECTED_LOC) VALUES (31001, '2021-02-28', 'Áß¶û±¸', '¸Æµµ³¯µå')

SELECT SERIAL_NUM, CONFIRMATION_DAY, INFECTED_LOC FROM CORONA WHERE SERIAL_NUM=:x

DELETE FROM CORONA WHERE SERIAL_NUM =:x

