SELECT
        E.ENAME, D.DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    
SELECT DEPTNO FROM DEPT
MINUS
SELECT DEPTNO FROM EMP    
    
    
-- MEM, DVD, RENT TABLE 에서의 조인    
SELECT

    FROM MEMBER MEM, DVD D, RENT R
   WHERE MEM.MEM_ID = R.MEM_ID
     AND D.DVD_CD = R.DVD_CD         
     