
SELECT * FROM EMP

SELECT JOB, DEPTNO, ENAME
   FROM EMP
   WHERE 

SELECT SAL, 
        DECODE(JOB, 'CLERK', SAL, NULL),
        COMM,
        DECODE(COMM, NULL, 'NULL')
  FROM EMP
  
SELECT JOB,
       DECODE(JOB, 'CLERK', 'C', 'MANAGER', SAL, NULL) JOB,
       DEPTNO
  FROM EMP
  ORDER BY DEPTNO

  
SELECT SUM(DECODE(JOB, 'CLERK', SAL,NULL))
  FROM EMP
UNION ALL  
SELECT AVG(DECODE(JOB, 'CLERK', SAL,NULL))
  FROM EMP  
  
SELECT DECODE(JOB, 'CLERK', SAL,NULL)
      ,DECODE(JOB, 'MANAGER', SAL,NULL)
      ,DECODE(JOB, 'CLERK',NULL,'MANAGER',NULL,SAL)
  FROM EMP      

SELECT SUM(DECODE(JOB, 'CLERK', SAL,NULL))
      ,SUM(DECODE(JOB, 'MANAGER', SAL,NULL))
      ,SUM(DECODE(JOB, 'CLERK',NULL,'MANAGER',NULL,SAL))
  FROM EMP 

------------------------------------------------------------------

SELECT DEPTNO, ENAME FROM EMP

SELECT ENAME FROM EMP GROUP BY ENAME

SELECT DEPTNO FROM EMP GROUP BY DEPTNO

SELECT DEPTNO, ENAME FROM EMP GROUP BY DEPTNO --실행불가

SELECT DEPTNO, ENAME FROM EMP GROUP BY DEPTNO,ENAME 
-- 문법적으론 문제가 없으나, 실질적인 의미가 없다.

SELECT DEPTNO, MAX(ENAME), MIN(ENAME) FROM EMP GROUP BY DEPTNO
-- 문법적으론 문제가 없으나, 실질적인 의미가 없다 2.
  