SELECT * FROM T_WORKTIME

SELECT ROWNUM RNO, WORKCD_VC, TIME_NU
  FROM ( SELECT WORKCD_VC, TIME_NU FROM T_WORKTIME
         ORDER BY TIME_NU ASC)
         
SELECT WORKCD_VC, TIME_NU, RANK() OVER(ORDER BY TIME_NU)
  FROM T_WORKTIME
  
SELECT WORKCD_VC, TIME_NU, 
      RANK() OVER(PARTITION BY WORKCD_VC ORDER BY TIME_NU)RNK
  FROM T_WORKTIME          
-------------------------------------------

Q. 작업시간이 짧은순서대로 번호를 붙여서 정렬해보기.

SELECT * FROM T_WORKTIME

SELECT * FROM T_WORKTIME A, T_WORKTIME B

SELECT A.WORKCD_VC, A.TIME_NU
  FROM T_WORKTIME A, T_WORKTIME B
 WHERE A.TIME_NU = B.TIME_NU

SELECT A.WORKCD_VC, A.TIME_NU
  FROM T_WORKTIME A, T_WORKTIME B
 WHERE A.TIME_NU > B.TIME_NU(+)

SELECT A.WORKCD_VC, A.TIME_NU
  FROM T_WORKTIME A, T_WORKTIME B
 WHERE A.TIME_NU >= B.TIME_NU

A. 
SELECT A.WORKCD_VC, A.TIME_NU, COUNT(B.SEQ_VC) RNK
  FROM T_WORKTIME A, T_WORKTIME B
 WHERE A.TIME_NU > B.TIME_NU
 GROUP BY A.WORKCD_VC, A.TIME_NU
 ORDER BY COUNT(B.SEQ_VC) ASC

----------------------------------------------
SELECT * FROM EMP
ORDER BY DEPTNO

SELECT * FROM DEPT
--
SELECT DEPTNO
FROM EMP

SELECT DEPTNO, ENAME
  FROM EMP
GROUP BY DEPTNO,ENAME

SELECT *
  FROM EMP E, DEPT D
  WHERE E.DEPTNO = D.DEPTNO
  ORDER BY EMPNO
  
SELECT *
  FROM EMP E, DEPT D
  WHERE E.DEPTNO(+) = D.DEPTNO
----------------------------------------------
       